### ISSUE TITLE
Deduplicated Content-Disposition headers on blobs

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-api#102]
As mentioned in #97, if we set `Content-Disposition` headers on blobs, we will need to choose a filename to use. If a blob is referenced twice with two different filenames, there may be a conflict and users would get the wrong filename when they download.

**Comment by waxlamp** [comment]
Would we not set that header dynamically based on which dandiset the user is browsing etc.?

**Comment by satra** [comment]
@waxlamp - this is about direct download from s3. here is the current situation via girder. we just want to ensure the s3 blob urls return similar content-disposition, which i believe is stored in the metadata of the s3 key of that blob.

```
$ curl -I https://girder.dandiarchive.org/api/v1/item/600da51598a84bac07caec8f/download
HTTP/1.1 303 See Other
Server: nginx/1.14.0 (Ubuntu)
Date: Wed, 10 Feb 2021 18:32:24 GMT
Content-Type: text/html;charset=utf-8
Content-Length: 1692
Connection: keep-alive
Allow: DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT
Girder-Request-Uid: 30f11c3a-5495-4d62-b086-74e977b67e12
Location: https://dandiarchive.s3.amazonaws.com/girder-assetstore/6d/45/6d459d7889b04bf2a80d3211aa54ae39?<REMOVED>
Strict-Transport-Security: max-age=63072000

$ curl -I https://dandiarchive.s3.amazonaws.com/girder-assetstore/6d/45/6d459d7889b04bf2a80d3211aa54ae39
HTTP/1.1 200 OK
x-amz-id-2: c4S4VnR9mdjWrliPF2jzBsRj3bF4I86tgsgjTxVdRgSxIYPpbEE8fc7woPVRATmdQK0eXe/y+vA=
x-amz-request-id: J248EZGJN8ZQN5X7
Date: Wed, 10 Feb 2021 18:30:43 GMT
Last-Modified: Sun, 24 Jan 2021 16:47:54 GMT
ETag: "1c41def924184940991785fc8725f256-175"
Content-Disposition: attachment; filename="sub-YutaMouse20_ses-YutaMouse20-140321_behavior+ecephys.nwb"
x-amz-meta-uploader-ip: 129.170.233.9
x-amz-meta-uploader-id: 5ee6c160155e470d51c94881
x-amz-version-id: qvIEoVh34LqShmSTloIQVBGmgE_TJBQl
Accept-Ranges: bytes
Content-Type: application/octet-stream
Content-Length: 11694713998
Server: AmazonS3

```

**Comment by waxlamp** [comment]
Ah I see. Do you have a dedup policy in mind for what filename to give the user when multiple uploads are backed by the same blob?

**Comment by yarikoptic** [comment]
oh, a tricky one... Since one dandiset's `empty.dat` could be another's `README.md`, I do not think we should provide `filename=` if we had some top level `GET /blobs/{sha256}`.  And thus for the current `/dandisets/{version__dandiset__pk}/versions/{version__version}/assets/{uuid}/download` filename should indeed come from the metadata record for that asset UUID.  No duplication etc.  So the question is if it is possible to redirect to S3 URL while providing those additional `Content-` response fields? quick search just lead to https://stackoverflow.com/questions/11163180/content-disposition-with-302-redirect which is "non conclusive/not advised" but I wonder if there is a native AWS S3 way?

**Comment by yarikoptic** [comment]
Overriding Response Header Values on https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html suggests that it is possible but we "must sign the request, either using an Authorization header or a presigned URL, when using these parameters. They cannot be used with an unsigned (anonymous) request." so we would not be able to just redirect but would need to mint pre-signed URLs for this purpose  (girder most likely, didn't check, just set Content-Disposition for the key, since they were not checksum based and thus "unique")

**Comment by satra** [comment]
@waxlamp  and @yarikoptic - @dchiquito  and i decided that the edge case of when the same blob is in multiple dandisets at different locations will be rare till we get to virtual dandisets. so for the moment any blob would likely have only one filename and we can use the most recent filename to associate with the blob.

regarding empty files. that should be an easy use case since the checksum of an empty file is fixed. (also i certainly hope that other than special cases we don't allow empty files to be uploaded)

**Comment by yarikoptic** [comment]
> would likely have only one filename and we can use the most recent filename to associate with the blob.

it is not uncommon for some .json files in bids to be identical across subjects/sessions.  Altogether I would not count on "likeliness" - it would lead to surprises later on.

re empty files: it was just the most obvious example, but I could come up with more not so obvious (README.txt -> README.md renames, etc -- remember that we will have publishing/releases, and files could simply be renamed between them)

Having said that -- "personally" I do not care much since dandi-cli would not care, and git-annex would not care.  But whenever people would click on a file X and the browser would download a file Y I bet it will cause confusion/anger/bug reports. Either it may be due to "uploader" error (e.g. uploading the same file under two different names) or renames -- users would not care, they would just get confused etc.  So, postponing solving this properly while working on this to start with would just delay and possibly amplify the pains later.

**Comment by waxlamp** [comment]
I agree with @yarikoptic that we should at least have some defensive idea of what we could do as a fallback. Here is one crazy idea: simply concatenate all the filenames that conflict, and let the user rename their local file after download. That would be something like `filename1.ext,filename2.mp4` rather than simply preferring the final name in the list.

One obvious problem with this is that this is confusing. Another is the weird corner case where someone likes to name their files with a comma separated string of dot separated fields. Ultimately, these may not matter much, since downloading directly from S3 seems like a power user thing, so perhaps we can treat such users as having waived their rights to not be confused at that point.

The major risk here is the potential for exposing the fact that someone else's dandiset contains the exact same file blob as yours. But this risk is largely (entirely?) mitigated by the fact that, by design, dandiarchive.org is supposed to be an open data portal, backed by a publicly accessible bucket--is that right?

**Comment by satra** [comment]
@waxlamp 

download options:
1. UI link
2. CLI download (either using UI link or as dataset)
3. s3 bucket (asset yaml file link - whaterver the contentURL link would be in the metadata)

we need to ensure that in all these cases doing a wget/curl returns a proper filename not a checksum

**Comment by satra** [comment]
superceded by #152
