### ISSUE TITLE
Use multipart for blob copy

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-api#103]
During the upload process, blobs are initially uploaded to a temporary location, then copied to the official `blobs` location after being validated. Currently this copy operation uses the S3 API `copy_object`, which is limited to 5GB files. There is an API to use [multipart copy](https://docs.aws.amazon.com/AmazonS3/latest/userguide/CopyingObjctsMPUapi.html), but this is considerably more involved so it was not done initially.

This should be implemented before people start uploading very large files.

**Comment by satra** [comment]
@dchiquito - would it then make sense to implement a slightly different route right away, since many of the files are over 5G in the current archive. so this would be a blocker if not tackled as part of the initial migration.

a thought yarik had around this was the following:

1. generate the urls for upload to directly reflect the checksum in blob location. so (s3://dandiarchive/blobs/<3>/<3>/<rest of checksum>). this only needs to be created if the checksum doesn't exist. 
2. create a lock file alongside this: (s3://dandiarchive/blobs/<3>/<3>/<rest of checksum>.lock)
3. store the lock with the user's identity in the db.
4. remove the lock on validate or allow the user to remove the lock (if the user does so, it should remove the associated blob)

this would let us go straight to location without a remote copy. wdyt?

**Comment by satra** [comment]
pinging @yarikoptic in case he had thoughts around the above flow.

**Comment by dchiquito** [comment]
Multipart copy shouldn't be difficult, but I wanted to get upload unblocked as soon as possible, so I opted for the <5GB copy for right now. If multipart copy is a blocker (which apparently it is) then I will do that soon/next.

That upload scheme would probably work, but it would involve more bookkeeping, bugs would be riskier, and it would require a substantial overhaul of how uploads are currently done, which would be time consuming. The issues I see are with malicious or buggy clients feeding it bad data, which might overwrite published blobs if not properly safe guarded. I think the current system is simpler and more robust, at the cost of that copy operation.

**Comment by satra** [comment]
if it's a simple copy replacement, let's do that to start with. let's keep the above workflow in mind, since the copy operation on TB size files (we need to upload one soon to the current archive) could take a while.

**Comment by dchiquito** [comment]
This has been added to #104
