### ISSUE TITLE
Generate `assets.yaml` file on publish

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandi-api#139]
See [comment below](https://github.com/dandi/dandi-api/issues/139#issuecomment-787520447) for more details.

**Comment by waxlamp** [comment]
@satra @yarikoptic: I missed this portion of the meeting from earlier today, but wanted to capture the requested feature in an issue. Could you fill in the issue description to provide more context and detail? Thanks!

**Comment by yarikoptic** [comment]
I will leave it to @satra to put the final version into the description but I believe the overall idea is for each `<dandiset_id>` release 
 `<version_id>` of a dandiset produce (under I think `/dandisets/<dandiset_id>/<version_id>/` prefix/directory) two files :
- `dandiset.json` (or `.yaml`?) -- return of `​/dandisets​/{dandiset__pk}​/versions​/{version}​/`  end point (might need similar to #136 change to just return metadata record)
- `asssets.json` (or `.yaml`?) -- return of `/dandisets/{version__dandiset__pk}/versions/{version__version}/assets/` end point "results" field when ran without pagination

**Comment by satra** [comment]
yes, the s3 store should contain:

```
/dandisets
  /dandiset_id
    /version
      dandiset.yaml
      asset.yaml (objects could be sorted by path)
```
for version == `draft` this can be populated with a cron-job (periodically). for any published version, this should happen on publish (and should include additional publishing metadata).

in terms of format, indeed the ideal `GET` on a dandiset (`/dandisets/{dandiset__pk}/versions/{version}/`) should just return the metadata similar to an asset. including populating this property of the metadata: https://github.com/dandi/dandi-cli/blob/master/dandi/models.py#L456

for assets, i think this should be a two step process. `/dandisets/{version__dandiset__pk}/versions/{version__version}/assets/` - i think this should continue to return uuids, paths to keep things simple. and any external code can iterate over the paginated returns.  for the s3 publishing process, this can happen internally to yield populated asset metadata of all assets in a dandiset. by internally, i mean it can call the python utils internally rather than calling the rest api endpoint. 

assets.yaml would be a serialized object array of metadata in order of sorted path values (since identifier is uuid).

the publishing process needs to lock the dandiset from modification. for the purpose of migration, it would be good to get some version of dandiset.yaml and assets.yaml written out even if the details are somewhat maleable, just to iron out this locking process in relation to uploads happening at the same time. (imagine labmate a is uploading by while labmate b hits publish).

**Comment by dchiquito** [comment]
@satra Publishing will now save a `dandiset.yaml` and `assets.yaml`. There are currently no dandisets with assets so generating `assets.yaml` isn't very demonstrable, but could you check that `dandiset.yaml` looks correct?
