### ISSUE TITLE
Re-investigate AWS S3 native verification of uploads and use ETag (with predefined block size logic)

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#146]
I feel in our chase for the optimal digest/hash that we are conflating multiple aspects:
- `A1` upload integrity validation
- `A2` validation of the digest (or digests! since could be multiple and we do want to provide some common non-adhoc one, like sha256) present in the asset metadata
- `A3` our desire to have our blob store hierarchy based on a commodity digest
- `A4` some potential assistance for 
   - A4.1: more efficient uploads - if we know that some blob is already present as a part of another file in the archive) and 
   - A4.2: downloads -- to validate and fail early if some portion is "not right". May be also for similar to A4.1 mechanism...

ATM we boiled down to use of sha256 for everything (besides considering A4) which would be nice/consistent. But sha256 poses technical challenges ATM due to its sequential nature. 
#145 is a discussion on using an alternative (hierarchical or any other "chunked" so could be estimated in parallel) primarily to solve `A1`, but potentially more useful if we decide to adopt it also for `A3`.  Regarding the other aspects

- `A2` - needs to be done out of band, there is no way around it as long as we want to provide commodity checksums (sha256 etc), and we should provide robust mechanism to validate those. We might want to actually completely disregard/remove digests provided by the client, besides the one to be used for validation, and then estimate digests we desire completely out of band.
- `A4` - all too hypothetical, and I think we should not bother/think about it; **and/or** adopt an existing platform which we could (ab)use for such functionality (ipfs?) instead of coming up with our own (thus see A2 for e.g. out of band ipfs CID calculation if we decide to support that). 

 So let's consider A1 + A3 (in particular if to be done in conjunction with #116), while relaxing the desire in A3 to be based on commodity digest in A2 (but still not be as random as girder had it). Two aspects to explore more IMHO:

1. get back to our attempts to provide verifiable (by S3 itself) uploads, which as we had done (in https://github.com/dandi/dandi-cli/pull/409 and then reverted in https://github.com/dandi/dandi-cli/pull/419) were not quite right: https://github.com/dandi/dandi-cli/issues/414#issuecomment-784347724 .  I think it is just a matter of finding out how to do that properly. E.g. if we need to provide md5 per chunk, we can do that on the client side for each chunk (from "Examples" of https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPart.html it seems that is needed).  But then how to validate the full file upload?  

2. alternative/complimentary: Couldn't we just use ETag to validate the uploads and then use it for A1 and A3?

Since we know the "chunks" splitting "rule" and know how AWS computes ETag (the md5sums of the chunks), why don't we do compute it on the client side and provide the server with it so it could validate that it is correct in `/validate`?  if we use that ETag also for A3, and store that information per blob record -- we can use it for detection of an already known blob... but also isn't it just the complimentary to `1.` if ETag is md5sum of individual md5sums then we could potentially do both - validate individual pieces (and retransmit if failed) and the entire file (since full ETag was provided).  If AWS later recomputes ETag (to e.g. be MD5 of the entire file) -- we do not really care. Validation against the value provided by S3 would be done only upon upload. 

Using built-in AWS S3 support for A1 + A3 we can completely avoid "validation cost" for uploads.

To get this working, we would just need to be the ones responsible to decide on parts (offset, sizes) based on a given file size, instead of offloading that to boto3 or others like a `MultipartManager` of https://github.com/girder/django-s3-file-field .

<details>
<summary>With this quick and dirty script</summary> 

```shell
#!/usr/bin/env python3.6
# based on https://teppen.io/2018/10/23/aws_s3_verify_etags/
# changed for our dandi logic on parts
import os
import sys
from hashlib import md5
from argparse import ArgumentParser

parser = ArgumentParser(description='Print out computed ETag of the multipart upload to dandi')
parser.add_argument('inputfile', help='The local file')
#parser.add_argument('etag', help='The etag from s3')
args = parser.parse_args()


# from https://github.com/girder/django-s3-file-field/blob/master/s3_file_field/_multipart.py
import math
from typing import Iterator, Tuple

def mb(bytes_size: int) -> int:
    return bytes_size * 2 ** 20

def gb(bytes_size: int) -> int:
    return bytes_size * 2 ** 30

def tb(bytes_size: int) -> int:
    return bytes_size * 2 ** 40



def _iter_part_sizes(#cls,
                     file_size: int) -> Iterator[Tuple[int, int]]:
    part_size = mb(64) # cls.part_size

    # S3 multipart limits: https://docs.aws.amazon.com/AmazonS3/latest/dev/qfacts.html

    if file_size > tb(5):
        raise Exception('File is larger than the S3 maximum object size.')

    # 10k is the maximum number of allowed parts allowed by S3
    max_parts = 10_000
    if math.ceil(file_size / part_size) >= max_parts:
        part_size = math.ceil(file_size / max_parts)

    # 5MB is the minimum part size allowed by S3
    min_part_size = mb(5)
    if part_size < min_part_size:
        part_size = min_part_size

    # 5GB is the maximum part size allowed by S3
    max_part_size = gb(5)
    if part_size > max_part_size:
        part_size = max_part_size

    remaining_file_size = file_size
    part_num = 1
    while remaining_file_size > 0:
        current_part_size = (
            part_size if remaining_file_size - part_size > 0 else remaining_file_size
        )

        yield part_num, current_part_size

        part_num += 1
        remaining_file_size -= part_size


def calc_etag(inputfile, parts):
    md5_digests = []
    with open(inputfile, 'rb') as f:
        for _, partsize in parts:
            chunk = f.read(partsize)
            md5_digests.append(md5(chunk).digest())
    return md5(b''.join(md5_digests)).hexdigest() + '-' + str(len(md5_digests))

def main():
    filesize  = os.path.getsize(args.inputfile)
    # num_parts = int(args.etag.split('-')[1])

    girder_etag = calc_etag(args.inputfile, _iter_part_sizes(filesize))
    print(f"ETag: {girder_etag}")

#    if args.etag:
#        print('Local file matches')
#        sys.exit(0)
#
#    print('Couldn\'t validate etag')
#    sys.exit(1)

if __name__ == "__main__":
    main()

```
</details>

I do verify etag correspondence for a tiny file:
```
$> wget -S -O testme https://api.dandiarchive.org/api/dandisets/001001/versions/draft/assets/872ad8bf-ee32-4b3d-8659-c85c4995cc86/download 2>&1 | grep ETag; ./file_etag.py testme
  ETag: "6ec084ca9d3be17ec194a8f700d65344-1"
ETag: 6ec084ca9d3be17ec194a8f700d65344-1
```
 but failed on the large one since my code reading was flawed and I did not realize that we are not using above approach, but just give it to boto3.
```
$> wget -S -O testme https://api.dandiarchive.org/api/dandisets/000003/versions/0.210225.1438/assets/f246e827-1a98-47a7-84c9-2e92fb68a5cc/download 2>&1 | grep ETag; ./file_etag.py testme             
  ETag: "390efa396f658cb9bf6f78eb05dbad8d-23"
^C
```
and if I follow the code I copied into above script I get considerably many more parts and code above selects minimal part size... so either that logic is not used (relying on boto3 one?) or was changed  since file was uploaded. @dchiquito might know.

After I adjust the logic, I expect to get a match ;)

NB: to facilitate possible future checksum migrations etc, for `A3` (blob store layout) we should not use any digest directly (as now sha256, or the suggested etag) but encode it into a multihash and use that one in the DB table (under `multihash` name) and in the layout (A3) on S3.

But WDYT in general?

**Comment by satra** [comment]
here are some potential issues with the etag approach besides no commitment as to how it's computed and that md5 is a week hash.

- there is no guarantee that some arbitrary combination of data and parts will not result in the same etag.
- the number of parts is not fixed from file to file on upload. thus even if two files are uploaded with the server generating different numbers of parts, you would get different etag for the same blob. 
- when someone downloads the file, they will not be able to verify it using the etag without knowing what the chunking blob size was.

in general indeed we need to be able to verify upload, and hopefully we can do that using MD5 content method. then we need to compute some form a checksum that has a guarantee to be recomputable. if we are going to provide any standard checksum, we will need to compute them on both the client and the server side to verify, but this can be out of band. we just need to ensure that whatever we are using in the blob storage in consistent.

for sake of argument we could use a uuid in the blob storage and have a mapping to checksums in the db. on any future upload, the database can tell you which uuid corresponds to that checksum and help a client not upload. this is more database manipulation but would allow one to simply verify the integrity of the blob on upload and leave any checksum verifications to be out of band with dedicated service. this would still allow deduplication but without the name being content addressable saving the necessity to decide on a checksum for blob storage. however, this would mean the checksums have to be linked to the uuid somewhere for any future verification, whether in a assets.yaml or in a db or we can write out a uuid to checksum table in the blob storage as well or for s3 generate redirectable objects.

**Comment by yarikoptic** [comment]
> * there is no guarantee that some arbitrary combination of data and parts will not result in the same etag.

there is no such guarantee for **any** hash.  Probability AFAIK is very low though even for md5.  I believe that snapshots.debian.org also uses md5 and I once inquired with "but md5 is weak -- have you seen the collisions?" and the answer was "No".

But in general I agree -- stronger hash would be better but it is not automagically provided by AWS, and hence all these discussions.

To make ETag stronger our hash could incorporate the size (since we would know it) and even be a composition with eg. another md5 of the leading part of the file.  With those 3 I bet we would not see any collision in our life time, and could verify upload by taking solely ETag portion and size of the hash.  Extra first block hash would not be verifiable from S3 without download of the first block (but we could make it md5 of just first 100k so - cheap) though but would allow for extra collision avoidance (if any such ever happens).

> the number of parts is not fixed from file to file on upload. thus even if two files are uploaded with the server generating different numbers of parts, you would get different etag for the same blob.
> when someone downloads the file, they will not be able to verify it using the etag without knowing what the chunking blob size was.

that is the point of coming up with a fixed strategy -- dandi-api can mint upload urls following that fixed strategy and dandi-cli can compute it and it all can be VERY easily implemented.
We can even reserve a name for it in the multihash table (e.g. `dandi-aws-etag1`) ;-)  But yeap -- it would be of quite lower utility than better hashes. And we loose pragmatic advantage if S3 changes how they establish an ETag, or we move away from AWS to some other platform with some other "built-in" algorithm. Also for uploads other than made outside of the dandi-api/dandi-cli interaction, we will need to resort to out of band computation of the hash (which we would need to do anyways).

> if we are going to provide any standard checksum, we will need to compute them on both the client and the server side to verify, but this can be out of band. we just need to ensure that whatever we are using in the blob storage in consistent.

if we do not trust (and we don't since we "verify") the checksums provided by client beyond the one to be used for upload verification (and thus verified, ideally for free like ETag + size), there is really no point for a client to provide them. We will anyways need to compute them out of band, and populate in DB.  What is the benefit from having client provide them?

(I will digest the last paragraph later, can't grasp ATM ho it addresses any of the current issues, e.g. too long validation of the upload)

**Comment by satra** [comment]
> What is the benefit from having client provide them?

client really doesn't have to, but then the output of the server is potentially prone to mismatch, and catching that at the point of asset creation is perhaps useful.

**Comment by yarikoptic** [comment]
that is the point -- we can simply disregard/pop those other hashes provided by the client (and document that or even error out upload initiation if they are provided) since we can't guarantee their correctness.  But later we can compute the ones we might care about out of band, and assuming that we trust server -- we can guarantee them being correct. 
Such logic could be applied to the other fields of metadata which we can find mis-matching the ones extracted from the file -- and we might want to correct them and announce that to the user while replacing with corrected values.  Such metadata validation we should approach systematically (and probably later).  Thus for now I would just document that we do not expect other hashes, error if any other provided, and not bother with their validation (besides the custom one based on quick "built in" ETag).  That would solve upload validation issue right away, and with alternative upload strategy of #116 implemented sooner than later we would make "finalization" of the upload nearly instantaneous.

Re A4 - in principle, md5sums of each chunk used for ETag computation can be provided (if they aren't already matching what is given as ETags per each chunk) to the finalization and we could establish yet another table with those checksums per chunk, which client can consult and use for more efficient download, or even later we could use for more efficient upload by doing transfer of those blobs directly by a worker withing the cloud.  But I am still not sure if we should aim for such a custom solution.

note: one of the cons of custom hash and absence of sha256 would be for creation of datalad dandisets where we now verify that metadata sha256 matches the one of the git-annex, and paranoid me will need to recompute our own hash, but IMHO it is an ok price ;)

**Comment by satra** [comment]
we can touch on this tomorrow, but the size of the chunk cannot be fixed to anything other than 5G if you want a solution that accommodates the maximum size of the object on AWS s3, since AWS limits the maximum number of parts. if this changes for AWS or other s3 providers, this places a significant tie in that i would like us to consider. if we also allow other routes to upload (like aws cli, it would also prevent direct comparison of ETag). i would strongly consider alternatives, including using UUIDs before using ETags.

i like your layout and indeed for me the objectives (in order of my priority) are: verification of upload (A1), deduplication (approx A3 - but doesn't have to be implemented with a content addressable store), verification for clients downloading the data (A2), and efficiencies in upload/download (A4). 

i will also say that we may have to support more than binary blobs (i.e. zarr like blobs - so let's keep our options flexible)

**Comment by yarikoptic** [comment]
> but the size of the chunk cannot be fixed to anything other than 5G  ...

that is my point -- we do not fix chunk size to anything. We decide on the logic to determine the block size given the file size (which we know ahead of time anyways), and ATM explicitly limit to the max size (and error if it is larger).Whenever/if S3 allows larger files - we adjust the logic to accommodate larger sizes (depending on how they elevate the limit -- either larger chunks or more chunks).

> if we also allow other routes ...

for those cases we would need to do off band validation anyways (even if it was direct upload to S3 but not via our API which pre-mints URLs following our chunking logic). ETag computation, since chunked, can be easily parallelized/offloaded to multiple workers, so it has that desired feature so it would provide efficient means for off band computation.

**Comment by yarikoptic** [comment]
Re UUIDs - I am not opposed to having blobs identified by UUIDs (and using blob UUID for hash store, A3) and internal one-to-many UUID-to-hashes mapping, but we would still need to choose some hash which allows for efficient upload validation (A1) and possibly off band validation (A2). But a plain UUID (as opposed to a multihash of some hash) offers no advantage IMHO (besides may be a fixed length for a DB column and uniform appearance) as a key for the blob "identification", and clearly provides no solution for validation.  So not sure what problem it would solve at this point.

**Comment by satra** [comment]
> we do not fix chunk size to anything

as much as i would like to see this, i think it would require a new multihash type configuration `<hash algo><chunksize><checksum>` . i'm not opposed to this and probably a good thing to consider. what i'm opposed to is binding us into using this as a prefix for the blob store. this is where i'm leaning more towards UUIDs. 

> So not sure what problem it [UUID] would solve at this point.

whatever we use in the blob store requires a decision now and using UUIDs decouples deduplication from content addressing. content addressing can be a logical thing in the metadata (always verifiable - as long as the algorithm is known). it also makes verification out of band from the content address. you can indeed use ETag for now to do this, but does not bind us to using this as the prefix. 

my proposal would be: 

A1. at the moment AWS is verifying that an upload is proper, just not the content. the CLI could check that the returned ETag matches the MD5 of the chunk that was sent. if not it could try again. the API server cannot ever determine if the right chunks were sent without internal validation (opening the file, doing things with it). so if the intent is upload verification. thus the fact that the upload completes should be sufficient for now. the only thing i think that the API would verify is content size matches the metadata.

however the other piece we need for deduplication is identity, because the CLI or some upload app has to check if the blob is already in the store. this is where some type of consistent algo has to come into play. and while we can use ETag as one form of identity, we should enable other forms as well. for the moment i would say we implement possibility for multiple identities, but move ahead with `ETag:chunksize` (we are likely to have both multipart and non-multipart blobs). but we don't use this for blob store prefix.

A2. out of band validation - this can work on dandisets or files: JSON is readable, NWB/NIfTI is parseable, conforms to BIDS, compute checksums, etc.,. so all blobs are marked non-valid till it computes. this can inject additional identities into the blob identity store. this will also simplify current api server validation services, and therefore should be able to continue with current celery implementation. and make this an AWS batch task or drogon task or some trusted task that runs with a cronjob.

A3. use UUID for the blob store and maintain a mapping table. when A2 completes we can add that information into the table and return with metadata of the file for digests. this would decouple our need to have a content addressable store, and someone else can always create the reverse mapping (e.g., sha256 -> uuid, blake3 -> uuid, ipfs -> uuid) and both sides would be unique. 

in the not so distant future, this blob could be a directory (e.g. zarr).

A4. upload: CLI check (like in A1) with retries for now. download: you can only verify the whole, but you would not be able to redownload a specific part easily i think without storing the md5 checksums of the parts somewhere. i don't think s3 keeps this after upload is complete. but we could consider storing this somewhere to help the CLI for larger blobs if we want to be able to verify on incremental chunks.

**Comment by satra** [comment]
A blob is referenced by a key generation function. the value of this key is used to index the blob in the database table of identities and on the s3 storage. `s3://dandiarchive/blob/<3digitskey>/<next3digitskey>/<restofkey>`

** database table of identities **: indexed by the key and contains columns for as many types of checksums as we want. these checksums constitute identities of the blob and should use functions that will always return the same value.

**key generation function**: the current suggestion (from satra) for this function is UUID4. 

**DANDI ETag generation function**: this is an agreement between API server and DANDI CLI for now to ensure there is an algorithm that consistently returns the correct number of parts given a `contentSize` in bytes. this should in theory also be the AWS ETag generation function.

**upload process**:
1. CLI initiates upload sending contentSize
2. generate key
3. API returns presigned URLs
4. CLI verifies that the number of URLs match the calculated number of parts (i.e. server and CLI are using the same ETag generation function)
5. CLI uploads to presigned URL and checks ETag on return
6. Completes upload and contacts API
7. API validates size and ensures object prefix matches computed ETag. 
8. Check for collision, since some other task could have finished by this time with the same object.
9. API moves the object into `s3://dandiarchive/blob/<3digitskey>/<next3digitskey>/<restofkey>` where key is returned by the key generation function. API returns this key to CLI.
10. API adds key + ETag into db.
11. API sends new key to trusted background process

**check process**
1. CLI sends expected digest with digest type (e.g., ETag)
2. API checks for existence of ETag in identity table. 
3. if exists, returns key, if not returns an error.

** garbage collection process **
1. if dangling key's are found, API does garbage collection on keys that are older than 24 hours.
2. sends background process info about deleted keys

** out of band background process **
1. Receives key from API and queues up a job to process the blob
2. performs a set of tasks on blob including multi checksum computation. 
3. adds checksums to object metadata
4. pings api that checksums are ready
5. API adds checksums to row in blob db

@dchiquito and @yarikoptic - here is an attempt to clarify the process.

@dchiquito  - does etag remain the same after you do a multipart copy/move from staging area to blob area? and with the above process with a uuid, would it now make sense to have the upload go directly into the blob store without a staging area?

**Comment by satra** [comment]
sure - in that case change the raw numbering to  use `1.` for everything (for easier adjustment). i forgot to do that.

**Comment by yarikoptic** [comment]
reinvestigated AFAIK and decided upon -- we are proceeding with AWS S3 Etags (as `dandi-etag`) to get an immediate validation
