### ISSUE TITLE
Q: S3 - what happens when multiple processes try to upload to the same key?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#151]
In light of #150 etc I wondered (although indeed basing keystore on uuid would be wiser, unless...) -- what happens if multiple processes request upload to the same key with the same part/chunk size?  
- will s3 refuse to generate upload urls with error that upload is already ongoing (and not finalized)
- will it generate such urls and allow to upload and then the first to finalize wins?
- will it somehow determine that a part is already uploaded? (thus possibly parallel uploads would just upload different chunks)

@dchiquito @satra - do you know?

**Comment by satra** [comment]
how would you get upload request to the same key? the key is uuid, so you should not ever get that.

**Comment by dchiquito** [comment]
I think the simplest solution would be to check if there is an existing Upload when calling `/uploads/initialize/`, so that the second client is simply not allowed to upload.

On the other hand, Satra described this: https://github.com/dandi/dandi-api/pull/150#discussion_r591904544. Both clients would start their uploads, but whoever called `/uploads/validate/` first and minted the AssetBlob first would win. The API would try to validate the upload of the second user, detect the existing AssetBlob, and simply use that AssetBlob instead of minting a new one.

**Comment by yarikoptic** [comment]
I am not trying to discuss an alternative solution (at least yet and at least not here ;)), and rather just wanted to find an answer to the specific question... might just try tomorrow.

As for current state of thinking on parallel/conflicting uploads -- yes, the first "validated"/"minted the AssetBlob" wins as we already described in our WiP https://github.com/dandi/dandi-api/pull/150/files#r592890971 and I also agree that it is a good way forward at minimal and very unlikely cost of two parallel uploads for the same blob. Having a look at that again lead me to spot a "typo" we (I think "I") introduced: https://github.com/dandi/dandi-api/pull/150/files#r592890971 for the "rejection" state.

**Comment by dchiquito** [comment]
Ah, I see. S3 doesn't care about multiple simultaneous uploads, whoever completes their upload last will overwrite the existing blob.

**Comment by satra** [comment]
only if they are writing to the same blob, which should never happen right, given the key is UUID and two uploaders of the same content get two different UUIDs?

**Comment by dchiquito** [comment]
Correct, I don't think this will matter for https://github.com/dandi/dandi-api/issues/154. @yarikoptic if that answers your question can you close?

**Comment by yarikoptic** [comment]
YES! Thank you!
