### ISSUE TITLE
me twice among "Ownership"

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#225]
may be somehow by design but not sure:  looking e.g. at 
https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/000007
there are danieladmin, debian@onerussian.com, ben.dichter@gmail.com, yarikoptic

so we have both debian@onerussian.com (probably email associated with github) and yarikoptic (github login)

**Comment by dchiquito** [comment]
This is because you are using a different email from the one you registered with Girder. Your django account is obviously `debian@onerussian.com`, but your girder account was `site-girder-dandi@onerussian.com`. The user migration script doesn't know to reconcile these, so it doesn't.

I think this is just some growing pains with the user migration. Can you close this if you're happy @yarikoptic ?

**Comment by yarikoptic** [comment]
that explains it.  Let's continue on https://github.com/dandi/dandi-api/issues/226 as for "name vs email"
