### ISSUE TITLE
E-mails: should we disclose (but then we must alert users about that) or not?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#226]
Currently , e.g. on https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/000007 , instead of some kind of a name or alias we show full emails. 
Ideally we could  take github's API approach, that non-authenticated requests have `null` for email, and authenticated - do return email.  But that is only  if user decided to make email public. I do not think it is worth the hassle.

The easiest solution would be ATM to never disclose emails.
But emails are also important for user to establish communication to the dataset's owners: we do have in the schema 

```
roleName: Optional[List[RoleType]] = Field(
        None, title="Role", description="Role of the contributor", nskey="schema"
    )
```
for each contributor. And RoleType could be `"dandi:ContactPerson"`.  May be for those we could disclose, but then again -- such "disclosure" should be articulated to users in some kind of terms of service they signed off on.

WDYT @satra et al?

**Comment by satra** [comment]
sometimes owners can have no role in the dandiset, so i would decouple the two. this is more about showing the name (from github oauth) instead of email for owners. i think that should be a simple change. 

the other piece is adding the first owner to the contributor list with roletype contact person when the dandiset is created. i think there should be an issue for this somewhere.

**Comment by dchiquito** [comment]
There are still some emails shown, such as https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/000003. These are from unmigrated users that haven't registered their GitHub accounts yet.
