### ISSUE TITLE
Do we really need "writing scope" from github oauth?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#280]
Follow up to https://github.com/dandi/dandiarchive/issues/679 .  The oauth redirect https://api.dandiarchive.org/oauth/authorize/ asks for "writing scope".  Is that the scope for operations on github  or on dandi-api?  if on github -- do we really need that?

in my github profile among oauth applications I see only `dandi-jupyterhub` and that one has only Read permissions.  Is that the "app" we use also for "dandi-api" login?

**Comment by waxlamp** [comment]
I think that GitHub itself provides just read-access, so that DANDI can know your email address, and I think "writing scope" means writing scope on dandi-api (I am guessing to perform actions such as creating a dandiset, or uploading data).

I agree that the authorization confirmation page could do a better job of explaining this stuff.

@brianhelba, can you confirm or update my understanding of how this works? And can you advise us on how the authorization page is generated, and whether/how we could provide more detailed information there if we wanted to?

**Comment by waxlamp** [comment]
> in my github profile among oauth applications I see only `dandi-jupyterhub` and that one has only Read permissions. Is that the "app" we use also for "dandi-api" login?

Mine lists `api.dandiarchive.org` as the name of the oauth app.

**Comment by brianhelba** [comment]
Yes, the page at `api.dandiarchive.org/oauth/authorize` is authorizing the DANDI GUI to be able to interact with the DANDI API.

Since the DANDI GUI does indeed generally need to make writes to the DANDI API, the "writing scope" is requested as part of the default configuration.

One simple way to avoid this confusion would be to configure Django Oauth Toolkit [to skip authorization](https://django-oauth-toolkit.readthedocs.io/en/latest/advanced_topics.html#skip-authorization-completely-for-trusted-applications) for the DANDI GUI specifically.

**Comment by waxlamp** [comment]
> One simple way to avoid this confusion would be to configure Django Oauth Toolkit [to skip authorization](https://django-oauth-toolkit.readthedocs.io/en/latest/advanced_topics.html#skip-authorization-completely-for-trusted-applications) for the DANDI GUI specifically.

This is a great idea, thank you @brianhelba.

**Comment by waxlamp** [comment]
I think this issue is resolved; if not, please re-open.
