### ISSUE TITLE
Add ability to login to Netlify deploy previews

### ISSUE THREAD

**Issue by AlmightyYakob** [dandi/dandi-api#309]
Currently we can't login to the staging API deploy from the Netlify deploy previews (due to redirect URIs), which means we can't use the meditor in those previews. We could get around this client side by adding enabling editing anyway in debug mode, but any changes would still fail when trying to send them to the API instance. Is there a reasonable way to allow this?

**Comment by waxlamp** [comment]
attn: @brianhelba

**Comment by brianhelba** [comment]
I believe a core part of the problem is that while you can whitelist wildcard CORS Origins, the code does not support having a wildcard for OAuth redirect URLs. As a general matter, an upstream feature to support wildcard matching of OAuth redirect URLs would probably present an unacceptable security risk if it was usable in production.

For DANDI, if this needs to be supported in testing only, it would be possible to [create a custom OAuth Application Model](https://django-oauth-toolkit.readthedocs.io/en/latest/advanced_topics.html?highlight=AbstractApplication#extending-the-application-model) and override [`AbstractApplication.redirect_uri_allowed`](https://github.com/jazzband/django-oauth-toolkit/blob/1.5.0/oauth2_provider/models.py#L122) (ideally for an Application which is only instantiated in the test environment).

**Comment by mvandenburgh** [comment]
Closed by #353, #379, and #383.
