### ISSUE TITLE
Any breaking change to the API should introduce a new .minor boost version tag

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#368]
Changes in `staging` (yet to pin point/address) broke dandi-cli (as CI must have told in that PR, yet to find). To make client more robust and be able to handle varying APIs, it needs to know the version of the API it is talking to.  #222 is the first step for that, but insufficient on its own for tests against dandi-cli to be able to stay green upon a breaking change.  

Although we are still in `0.` and "all bets are off", I think it would be a simple to adopt and to adhere-to strategy to finally start annotating for such changes by tagging `.minor` releases to the dandi-api. Currently dandi-api has only a single tag v0.0.1 (note: unannotated! so use `git describe --tags`) and thus staging ATM is v0.0.1-172-g2970034 (versioneer would have made it into `0.0.1+172.g2970034` semver).  In principle `dandi-cli` could rely on using that `+172` but that would be very suboptimal because might simply be incorrect for comparison for a state of some PR which doesn't have yet target branch (containing another `+172`) merged in some PR etc.

An alternative would be to annotate the brackage point with `0.nextminor.0-dev1` tag and then release `0.nextminor.0` whenever all desired changes/breackages are absorbed.

**Comment by waxlamp** [comment]
We are now in the process of performing releases to deploy to production, and we are generally incrementing the minor version number as we do so.

I'm not sure how your "breakage point" proposal helps. When things are in 0.x generally the idea is to pin exact versions, since compatibility information simply isn't guaranteed between releases (i.e., "all bets are off"). Can we just be more strict about the dandi-api integration testing, and make correlated fixes to `dandi-cli` as we develop? This would be the best option, as it would leave the deployed version of the API in sync with the `master` version of `dandi-cli`.

**Comment by waxlamp** [comment]
Upon re-reading the original report, it seems like we can close this issue now? Production releases now require a tagged release, so once we figure out how to reliably supply version information to Heroku for the build, the CLI should have all the info it needs.

**Comment by yarikoptic** [comment]
Well, I am ok to have it closed for now but we will come back to this whenever API matures since we cannot and will not be always in the 0.x land, and having PATCH and MINOR  and even MAJOR releases will come.  client will never have "all the info it needs" if every release of dandi-api breaks compatibility since then client would require constant upgrades, and eventually (whenever we start working on allowing multiple instances of dandi archive) we will need to avoid demanding a client per dandiarchive instance to have versions matched exactly.

**Comment by waxlamp** [comment]
> Well, I am ok to have it closed for now but we will come back to this whenever API matures since we cannot and will not be always in the 0.x land, and having PATCH and MINOR and even MAJOR releases will come. client will never have "all the info it needs" if every release of dandi-api breaks compatibility since then client would require constant upgrades, and eventually (whenever we start working on allowing multiple instances of dandi archive) we will need to avoid demanding a client per dandiarchive instance to have versions matched exactly.

When we decide that the API is ready for 1.0, then we will need to be far more careful about breaking changes. The reason many projects stay in 0.x for essentially their entire lifetimes is that it is indeed difficult to commit to a 1.0 semver workflow. But we are still in a research-type phase with API design where, e.g., we are reshuffling how some endpoints work because of performance issues, etc., and we are still nailing down things like publish and embargo workflows.

If we do want to get to 1.x faster, we can set aside a chunk of time to evaluate the API and see what is left for us to implement, redesign, and bugfix in order to get there. Once we're there, then indeed we would follow the bulk of semver thereafter (minor version bump for new features and for deprecations; patch level bumps for bugfixes, etc.; major level bump for breaking changes) and then the CLI would only need to worry about adding functionality when there's a minor bump, and shifting how it works for major bumps.

At the moment, whether we adopt a special sub-scheme within 0.x or not, we will largely be relying on automated testing to detect whether the API changes break the CLI. But breakages would seem to be both unavoidable in the current era of development, and not particularly manageable via semver. This is why I closed this issue, but perhaps we need to harden how testing is done to make ourselves confident in our workflow until we reach 1.x.
