### ISSUE TITLE
Unify production and staging deployments

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#404]
ref https://github.com/dandi/dandi-api/pull/402#issuecomment-877234064 :

 staging relies on heroku's way to fetch the branch, whenever production relies on https://github.com/dandi/dandi-api/blob/master/.github/workflows/production-deploy.yml which is triggered only on releases. IMHO should be harmonized to always be done by that github action.  I think it might help to ensure that we have needed for versioneer git tags (FWIW, I did push one sample tag to heroku's git repo for the dandi-api app)

**Comment by waxlamp** [comment]
Will need to investigate this. The github action we invoke for production deployment uses [Heroku's git workflow](https://devcenter.heroku.com/articles/git), and I'm not sure if the final result is different from Heroku's autodeploy, since both are going to use the Python buildpack, etc.

@brianhelba may already know enough to weigh in on this.
