### ISSUE TITLE
editing metadata resulting in summary generation errors on production

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#430]
in this dandiset it says it is unable to generate asset summary: https://gui.dandiarchive.org/#/dandiset/000108

**Comment by dchiquito** [comment]
I think the problem is invalid asset metadata. I add logging in #434 to help identify exactly what is going wrong.
Long term #417 should show exactly what asset metadata is incorrect, which is the better solution.

**Comment by satra** [comment]
let's find out.

**Comment by dchiquito** [comment]
>Jul 21 09:58:21 dandi-api app/web.1 [16:58:21] ERROR    Error calculating assetsSummary               version.py:251
Jul 21 09:58:21 dandi-api app/web.1                     Traceback (most recent call last):                          
Jul 21 09:58:21 dandi-api app/web.1                       File "/app/dandiapi/api/models/version.py",               
Jul 21 09:58:21 dandi-api app/web.1                     line 245, in _populate_metadata                             
Jul 21 09:58:21 dandi-api app/web.1                         summary = aggregate_assets_summary(                     
Jul 21 09:58:21 dandi-api app/web.1                       File "/app/.heroku/python/lib/python3.8/sit               
Jul 21 09:58:21 dandi-api app/web.1                     e-packages/dandischema/metadata.py", line                   
Jul 21 09:58:21 dandi-api app/web.1                     297, in aggregate_assets_summary                            
Jul 21 09:58:21 dandi-api app/web.1                         _add_asset_to_stats(meta, stats)                        
Jul 21 09:58:21 dandi-api app/web.1                       File "/app/.heroku/python/lib/python3.8/sit               
Jul 21 09:58:21 dandi-api app/web.1                     e-packages/dandischema/metadata.py", line                   
Jul 21 09:58:21 dandi-api app/web.1                     282, in _add_asset_to_stats                                 
Jul 21 09:58:21 dandi-api app/web.1                         if "nwb" in assetmeta["encodingFormat"]:                
Jul 21 09:58:21 dandi-api app/web.1                     KeyError: 'encodingFormat'                                  

@satra Seems like there is at least one asset without an `encodingFormat`, which breaks `aggregate_assets_summary`.

Since this is an error caused by invalid data and it should be communicated more clearly in the future, I think this should be closed.

**Comment by satra** [comment]
that seems weird that it would not have `encodingFormat`.  @yarikoptic - we can track this down, but i'm assuming the CLI should have caught this before uploading.

**Comment by satra** [comment]
found all the issues, and i'll file a CLI issue for the encodingFormat.

```
{'status': 'Invalid', 'validation_error': '1 validation error for PublishedAsset\ndigest\n  Digest is missing dandi-etag or sha256 keys. (type=value_error)', 'identifier': '0180425a-4b00-4805-8e48-90b8febd13d0'}
{'status': 'Invalid', 'validation_error': '1 validation error for PublishedAsset\ndigest\n  Digest is missing dandi-etag or sha256 keys. (type=value_error)', 'identifier': '19f7ee12-3c53-4b21-9daf-8277e624b9d1'}
{'status': 'Invalid', 'validation_error': '1 validation error for PublishedAsset\ndigest\n  Digest is missing dandi-etag or sha256 keys. (type=value_error)', 'identifier': '71317642-cd8f-4690-8fcc-245d03700e00'}
{'status': 'Invalid', 'validation_error': '1 validation error for PublishedAsset\ndigest\n  Digest is missing dandi-etag or sha256 keys. (type=value_error)', 'identifier': '9e0506e5-f4a4-4067-92ba-e198117090b2'}
{'status': 'Invalid', 'validation_error': '1 validation error for PublishedAsset\ndigest\n  Digest is missing dandi-etag or sha256 keys. (type=value_error)', 'identifier': 'd1531f22-4889-4529-ac21-f649b97d32eb'}
{'status': 'Invalid', 'validation_error': '1 validation error for PublishedAsset\ndigest\n  Digest is missing dandi-etag or sha256 keys. (type=value_error)', 'identifier': '5e8f20be-79fd-469e-80dc-0264e56b323b'}
{'status': 'Invalid', 'validation_error': '1 validation error for PublishedAsset\ndigest\n  Digest is missing dandi-etag or sha256 keys. (type=value_error)', 'identifier': 'd926cd89-bcec-47e7-bc1a-247fea1945a8'}
{'status': 'Invalid', 'validation_error': '1 validation error for PublishedAsset\ndigest\n  Digest is missing dandi-etag or sha256 keys. (type=value_error)', 'identifier': '44ea75ab-0631-4e69-a281-68c142f3c961'}
{'status': 'Invalid', 'validation_error': '1 validation error for PublishedAsset\ndigest\n  Digest is missing dandi-etag or sha256 keys. (type=value_error)', 'identifier': '112d3bf7-7ed4-4679-a4c4-9008975953de'}
{'status': 'Invalid', 'validation_error': '1 validation error for PublishedAsset\ndigest\n  Digest is missing dandi-etag or sha256 keys. (type=value_error)', 'identifier': '89d1a217-5825-4883-bc87-c32f38a14301'}
{'status': 'Invalid', 'validation_error': '1 validation error for PublishedAsset\ndigest\n  Digest is missing dandi-etag or sha256 keys. (type=value_error)', 'identifier': '3cc118b8-ef79-4070-b40d-636d928e6ade'}
{'status': 'Invalid', 'validation_error': '1 validation error for PublishedAsset\ndigest\n  Digest is missing dandi-etag or sha256 keys. (type=value_error)', 'identifier': '9551cedf-6cba-406f-8ec7-b486780f0742'}
{'status': 'Invalid', 'validation_error': '1 validation error for PublishedAsset\ndigest\n  Digest is missing dandi-etag or sha256 keys. (type=value_error)', 'identifier': 'df2aab5f-28b6-454c-9453-6cbc50bb8c9b'}
{'status': 'Invalid', 'validation_error': '1 validation error for PublishedAsset\ndigest\n  Digest is missing dandi-etag or sha256 keys. (type=value_error)', 'identifier': '910bdd02-042a-4c7f-9a08-6b3a04abbce3'}
{'status': 'Invalid', 'validation_error': '1 validation error for PublishedAsset\ndigest\n  Digest is missing dandi-etag or sha256 keys. (type=value_error)', 'identifier': '56fa408a-4c4d-4d3a-8daa-28e10326b4d5'}
{'status': 'Invalid', 'validation_error': '1 validation error for PublishedAsset\ndigest\n  Digest is missing dandi-etag or sha256 keys. (type=value_error)', 'identifier': 'ccdd6c7d-3e6b-41ff-bc94-5d3f1e628df7'}
{'status': 'Pending', 'validation_error': '', 'identifier': '2a3f201a-d0f7-481f-9dfe-6b45303f788e'}
{'status': 'Pending', 'validation_error': '', 'identifier': '1a34a3d7-60d0-4238-800b-60ea20f82cbd'}
{'status': 'Pending', 'validation_error': '', 'identifier': '56f859f3-a361-4c09-ae06-4a776ae1952a'}
{'status': 'Pending', 'validation_error': '', 'identifier': '35e0788e-692d-4498-8982-a1aae381179e'}
{'status': 'Invalid', 'validation_error': 'Metadata version 0.3.0 is not allowed. Allowed are: 0.4.4.', 'identifier': 'e84b5900-bef1-494a-9399-7eaf537390bf'}
```

**Comment by yarikoptic** [comment]
`Metadata version 0.3.0 is not allowed` -- smells like old dandischema/client were used to upload, likely the `0.14.0 (Thu Apr 15 2021)` ... filed https://github.com/dandi/dandi-cli/issues/722

**Comment by satra** [comment]
i fixed the specific issue by deleting and reuploading the asset. other issues have been filed about metadata consistency.
