### ISSUE TITLE
Allow for upload/handling of a number/range of schema_version's

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#437]
To some degree a continuation of https://github.com/dandi/dandi-api/issues/172 .

We have `schema_version` (as provided by `/info/` end-point). It is a singular version and requires very tight coordination between growing number of components (dandi-api, web ui, dandi-cli) to make everything "kosher".  E.g. to prevent users uploading assets with metadata in older versions, thus known to be invalid etc,  https://github.com/dandi/dandi-cli/pull/724 is introducing the check so no assets in a different from `schema_version` of dandi-api would be uploaded.

ATM `schema_version` signals at least 2 things within dandi-api context:
- a version of the schema dandi-api "understands" as where to find/place digests etc.
- the version of schema provided by dandischema and used by dandi-api for `to_datacite`, `aggregate_assets_summary`, `validate` (and management command `migrate`).

But in dandischema we
- already support migration of metadata between some versions of the schema (at least at dandiset level) (what `migrate` does)
- [WiP in dandischema/pull/60](https://github.com/dandi/dandischema/pull/60/files#diff-fca559c50b570e7d5a8bc3aace5e144a9cf0810d05f15879e7da7d4569bcedb5R10) with extra discussion in https://github.com/dandi/dandischema/issues/22#issuecomment-884907346 to support validation of multiple schemas .

So overall, AFAIK dandi-api isn't really the one which really cares about seeing a singular specific version of schema as long as that version remains consistent with placement of the few metadata fields which dandi-api relies on.  The rest (validation etc) falls under purview of dandischema, and as soon/long as it provides support for validating (or possibly even migrating?) metadata - dandi-api should just inform (in `/info/`) about versions of metadata schema it can allow for upload and expect them being validated ok (if they are valid in that version). And that information should be provided by `dandischema`.

So I am thinking that it should expose `allowed_schema_versions` as to what schema_versions to be allowed to be uploaded and be expected to be "valid".  We might decide to expose multiple variables or just make it into a dict to signal what versions are "natively" supported or dandi-api would attempt metadata migration to target `schema_version`, so could even be such a dict as

```json
"schema_version": "0.5.5",
"schema_versions": {
  "0.4.4": "migrate",
  "0.5.0": "native"
}
```
or something alike (may be making `"migrate"` into `{"support": "migrate"}` so later we could add other qualifiers).  Then clients could be aware that if "migrate", the resultant metadata would not necessarily match the uploaded one, and might also expect migration error to be returned.

Semantic/logic (echoing #172) might want to be added to allow for specifying schema ranges, e.g. in above all "0.4.x" after "0.4.4" would also be migrated, and all after "0.5.0" are natively supported, so even though dandi-api uses "0.5.5", "0.5.99" would also be natively supported since didn't introduce any backward incompatibility.

Attn @satra @waxlamp

**Comment by satra** [comment]
i like this approach a lot to enable some of the behind the scenes migration of metadata. to consolidate this, we may want to put the json specification in dandischema itself, so that the above spec is returned by whichever version of dandischema is in use. what the api server could do is make sure we don't go backwards by mistake. so it can store the version in the db and if on deployment the version regresses, it can raise an error.

also this means we can introduce a function called `process` in dandischema, which could be called on any metadata save function in the api. `validate` remains as is from the point of view of publishing. 

one thing to note is what happens if one `POST`s an existing asset to a new dandiset. we have not fully implemented this functionality, and my current preference would still be to keep the asset id intact till a modification is made. in such a case the `process` would have to take into account that this is a published asset somehow and not try to migrate it.

**Comment by waxlamp** [comment]
With the specification of allowed schema versions in dandischema's validation routines, I think this may be solved. Re-open otherwise.
