### ISSUE TITLE
Create management script to copy dandisets from another deployment

### ISSUE THREAD

**Issue by mvandenburgh** [dandi/dandi-api#516]
A script like this would be helpful for viewing production dandisets in staging, for example. Only the metadata for each dandiset should be copied, since we don't want to be transferring terabytes of asset data into our staging bucket.

**Comment by dchiquito** [comment]
From https://github.com/dandi/dandi-api/pull/517#pullrequestreview-756683425, some things I would want from a download script:
* Downloading a single dandiset. If I'm trying to solve a problem with specific metadata, I only want to download the problem dandiset.
* An option to replace a local dandiset + ID with the remote data. Delete the dandiset that was using that ID and replace it with the remote contents from scratch.
* An option to download some or all assets (default is off to prevent downloading too much accidentally)
* Download all the dandisets. When I'm initially setting up a new dev environment it would be easier to have one command to run rather than picking out some samples, but that's less important to me than downloading individually.
