### ISSUE TITLE
are staging "new user registration to review" addresses "correct"?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#612]
We were just pinged by @vikramvijayan that his account was not activated on staging server.  I see two pairs of emails for his registration 

```
   1 O   Nov 22 Vikram Vijayan   [Dandi] Dandi staging access
   2     Nov 18 admin@tropical-  [Dandi] DANDI: New user registered: XXX@gmail.com
   3     Nov 18 admin@tropical-  [Dandi] DANDI: Review new user: XXX@gmail.com
   4     Nov 18 admin@developme  [Dandi] DANDI: New user registered: XXX@gmail.com
   5     Nov 18 admin@developme  [Dandi] DANDI: New user registration to review: XXX@gmail.com
```
with the `5` looking like the one for staging (note different subject -- didn't check git history which one is "newer").   But URL in all of the emails points to https://api.dandiarchive.org/ and not staging.

**Comment by mvandenburgh** [comment]
Ah yes those emails have https://api.dandiarchive.org hardcoded  in them. I guess it is time to implement #286.

**Comment by yarikoptic** [comment]
> Ah yes those emails have https://api.dandiarchive.org hardcoded in them. I guess it is time to implement #286.

yes, please.

**Comment by waxlamp** [comment]
> > Ah yes those emails have https://api.dandiarchive.org hardcoded in them. I guess it is time to implement #286.
> 
> yes, please.

https://github.com/dandi/dandi-api/pull/613 will fix this, but that in turn requires a review for https://github.com/dandi/dandischema/pull/98 along with some operations stuff (new schema release, etc.).

**Comment by satra** [comment]
we cannot do a full split at this point as i noted in dandi/dandischema#98, so we either do the full decoupling, or a temporary fix as needed to address the current issue. 
 
 full decoupling will require:
 - instance specific prefix support (DANDI has a very specific meaning and maps on in specific places in the model) support in API and CLI
 - doi prefix (we are currently using prod/test datacite to parallel our needs, but technically this is like saying add a DOI prefix)
 - merging dandiarchive.org and gui.dandiarchive.org (so we are not dependent on a redirector, but we would need any of those functionalities somewhere -  a client side web app doesn't provide all those things - for example HEAD requests)
 - bucket location
 - schemas that are now dependent on these variables, and therefore separate context files generated by prefix and picked up by the api server
 - make gui.dandiarchive.org still responsive and redirecting in the short term.
 
i feel that this is not going to be done with just these PRs. in fact as i noted in the schema comment, the WEB_APP_URL should not be gui.dandiarchive.org but dandiarchive.org since we don't want to inject gui.dandiarchive.org anywhere in the metadata.

i would be fine with targeting full decoupling say by end of next week. but we will require several hands on deck regarding the different components, and will likely have to announce some downtime.

**Comment by satra** [comment]
and we need to understand if staging and production are truly to separate instances or we are talking paired decoupling. i.e. any site should be able to spin up the pair.
